= Implement Event-Driven Ansible

With the pieces all in place, and all the information gathered, we can now start to put it all together.

[#ios]
== IOS configuration

Now we can put together what we just found.

In your file explorer, under `playbooks`, take a look at the playbook `configure_ios_telemetry.yml`.

This playbook will have the job of configuring all our Cisco devices to send telemetry messages to Telegraf. There are several things to look at here.

* The hosts line: We are working with two devices, rtr1 and rtr2.
* The vars block: Our inputs for the playbook
 ** `telemetry_grpc_port` - We know from Exercise 3.1 that Telegraf is listening on port *8089*.
 ** `telemetry_nodes` - We know from Exercise 3.2 that the YANG node we want to listen for has prefix `interfaces-ios-xe-oper` and xpath `interfaces`.
* The first task: Enables the use of YANG on the device (we did this already for rtr1 but not rtr2).
* The second task: Creates push subscriptions to all the YANG nodes described in the `telemetry_nodes` variable.

Go ahead and run the playbook:

[source,bash,role=execute]
----
ansible-navigator run playbooks/configure_ios_telemetry.yml
----

In your terminal, ssh to `rtr1`. First we'll verify that the telemetry configuration is looking good.

[source,bash,role=execute]
----
ssh rtr1
----

[source,role=execute]
----
show telemetry ietf subscription 1
----

You may initially see a `Schema currently not available` message if you were quick, but eventually we should see this output:

----
ID         Type       State      State Description
1          Configured Valid      Subscription validated
----

Now let's make sure that this is producing messages in Kafka. Exit out of the router SSH session and run the following Kafka listener command.

[source,role=execute]
----
exit
----

[source,bash,role=execute]
----
sudo docker exec -it broker kafka-console-consumer --bootstrap-server localhost:9092 --topic eda | jq 'select(.tags.name=="Tunnel0")' | tee interface.json
----

NOTE: This is the same command from earlier, but with a couple addons. This is to help us filter out messages that are relevant to what we're doing, and persist to a file so we can more easily inspect the messages.

Wait for a message to appear in your terminal. It may take up to 30 seconds. Once one does, pres CTRL+C a couple times to stop the listener.

You should now have an `interface.json` file available in your file explorer. Open it so that we can see how the data is being formatted by Telegraf.

Your file should look like the following (some sections removed for brevity):

[source]
----
{
  "fields": {
    "admin_status": "if-state-up",
    "auto_downstream_bandwidth": 0,
    "auto_upstream_bandwidth": 0,
    "bia_address": "00:00:00:00:00:00",
[...]
  },
  "name": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
  "tags": {
    "host": "telegraf",
    "name": "Tunnel0",
    "path": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
    "source": "rtr1",
    "subscription": "1"
  },
  "timestamp": 1745445626
}
----

This is information about `Tunnel0`, the interface we were looking at previously, arranged in JSON format. It looks like `fields.admin_status` will be a good data point to use, and its normal value is "if-state-up". It also looks like we can use `tags.name` to identify that the message is about `Tunnel0` specifically, which will be useful since the subscription we set up is sending messages about every interface the router has.

NOTE: If you recall looking at the YANG tree in Exercise 3.2, you may notice that all the data available here matches up with that.

[#rulebook]
== Using ansible-rulebook

In your file explorer, expand the `rulebooks` directory. Then inside that directory, open the file `interface_status_cli.yml`.

This is a *rulebook* which is the mechanism for controlling Event-Driven Ansible, the same way a playbook controls regular Ansible.

* We have a Kafka source available on port 9092, which we know from Exercice 3.1. We can get access to that in EDA by using the `ansible.eda.kafka` *event source plugin*.
* We have a single rule
 ** The condition looks for `event.body.fields.admin_status` to be anything other than "if-state-up", which we identified in the previous exercise as the good/normal state.
 ** The condition also looks for `event.body.tags.name` to be "Tunnel0" (so that we don't trigger on other interfaces being down).
 ** The response to this condition is to run the configuration playbook - the same one we ran in Exercise 2.2 to recover from a misconfiguration.

While you're here, also take a look at `interface_status_aap.yml`. We aren't going to use it now, but we will later. Note the difference between the two rulebooks at the very end under `action`.

Now open another terminal. In your student workbench, at the top of the terminal, you have a `+` button. Click it, and you should have a new bash terminal come up. You can swap between them on the right. 

In your new terminal, run the following command:

[source,bash,role=execute]
----
ansible-rulebook --rulebook rulebooks/interface_status_cli.yml -i inventory
----

You should not initially see any output. This is normal, since no conditions are currently being met. For now, leave this alone and switch back to your original terminal.

What we want to do now is bring the `Tunnel0` interface down again and see if `ansible-rulebook` will react to it. Run the following commands from earlier:

[source,role=execute]
----
ssh rtr1
----

[source,role=execute]
----
configure terminal
interface Tunnel0
shutdown
end
----

Now, switch back to your `ansible-rulebook` terminal (using the navigation on the right side of the terminal - the right one will be labeled `python3` any time `ansible-rulebook` is running) and observe.

You will need to wait up to 30 seconds for the next Kafka message to come in, but once it does, you should see the playbook run. When it runs, you should observe a couple things:

* The task that applies interface configuration has reported `changed`
* The playbook has only run against rtr1. Recall from Exercise 2.1 there was an `ansible_eda` variable in the hosts line we were not yet using; now we are.

Press CTRL+C to stop ansible-rulebook. Switch back to your original terminal, which should still have an SSH session open to rtr1. Verify that the interface is up, then exit the SSH session.

[source,role=execute]
----
show ip interface brief
----

[source,role=execute]
----
exit
----

If desired, try running the same commands on `rtr2` and verify that everything works the same way there.

We now have a functioning self-healing network environment... as long as `ansible-rulebook` is running. We don't want to have that up in a terminal all the time, so let's move on and do something about that.
